DROP DATABASE IF EXISTS bd_sad;
CREATE DATABASE bd_sad;

DROP DATABASE IF EXISTS dw_sad;
CREATE DATABASE dw_sad;


-- CRIA AS TABELAS DA STAGE AREA

-- Cria tabela de pedidos
DROP TABLE IF EXISTS bd_sad.pedidos;
CREATE TABLE bd_sad.pedidos
(
  ORDER_ID BIGINT
, ORDER_DATE DATETIME
, CUSTOMER_ID BIGINT
, ORDER_STATUS BIGINT
, ORDER_TOTAL DOUBLE
, SALES_REP_ID BIGINT
, PROMO_ID BIGINT
, LINE_ITEM_ID BIGINT
, PRODUCT_ID BIGINT
, UNIT_PRICE DOUBLE
, QUANTITY BIGINT
)
;

-- Cria tabela de clientes
DROP TABLE IF EXISTS bd_sad.clientes;
CREATE TABLE bd_sad.clientes
(
  ACCOUNT_MGR_IDPHONE_NUMBER_2CUSTOMER_ID BIGINT
, CUST_FIRST_NAME VARCHAR(40)
, CUST_LAST_NAME VARCHAR(50)
, STREET_ADDRESS VARCHAR(50)
, POSTAL_CODE BIGINT
, CITY VARCHAR(30)
, STATE_PROVINCE VARCHAR(3)
, COUNTRY_ID VARCHAR(2)
, COUNTRY_NAME VARCHAR(30)
, REGION_ID BIGINT
, NLS_LANGUAGE VARCHAR(3)
, NLS_TERRITORY VARCHAR(11)
, CREDIT_LIMIT BIGINT
, CUST_EMAIL VARCHAR(50)
, PRIMARY_PHONE_NUMBER VARCHAR(30)
, PHONE_NUMBER_2 VARCHAR(30)
, ACCOUNT_MGR_ID BIGINT
, LOCATION_GTYPE BIGINT
, LOCATION_SRID BIGINT
, LOCATION_X DOUBLE
, LOCATION_Y DOUBLE
)
;

-- Cria tabela de representante de vendas
DROP TABLE IF EXISTS bd_sad.repvendas;
CREATE TABLE bd_sad.repvendas
(
  EMPLOYEE_ID BIGINT
, FIRST_NAME VARCHAR(30)
, LAST_NAME VARCHAR(50)
, EMAIL VARCHAR(50)
, PHONE_NUMBER VARCHAR(22)
, HIRE_DATE DATETIME
, JOB_ID VARCHAR(6)
, SALARY BIGINT
, COMMISSION_PCT INT
, MANAGER_ID BIGINT
, DEPARTMENT_ID BIGINT
)
;

-- Cria tabela de produtos
DROP TABLE IF EXISTS bd_sad.produtos;
CREATE TABLE bd_sad.produtos
(
  PRODUCT_ID BIGINT
, PRODUCT_NAME VARCHAR(40)
, LANGUAGE_ID VARCHAR(2)
, MIN_PRICE BIGINT
, LIST_PRICE BIGINT
, PRODUCT_STATUS VARCHAR(17)
, SUPPLIER_ID BIGINT
, WARRANTY_PERIOD INT
, WEIGHT_CLASS BIGINT
, PRODUCT_DESCRIPTION VARCHAR(1000)
, CATEGORY_ID BIGINT
, CATALOG_URL VARCHAR(80)
, SUB_CATEGORY_NAME VARCHAR(30)
, SUB_CATEGORY_DESCRIPTION VARCHAR(100)
, PARENT_CATEGORY_ID BIGINT
, CATEGORY_NAME VARCHAR(30)
)
;


-- Cria tabela de promoções
DROP TABLE IF EXISTS bd_sad.promocoes;
CREATE TABLE bd_sad.promocoes
(
  PROMO_ID BIGINT
, PROMO_NAME VARCHAR(30)
)
;


-- CRIA AS TABELAS DO DATA WAREHOUSE

-- Cria tabela de clientes
DROP TABLE IF EXISTS dw_sad.dim_clientes;
CREATE TABLE dw_sad.dim_clientes
(
  CLIENTE_DIM_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY
, version INT
, date_from DATETIME
, date_to DATETIME
, CUSTOMER_ID BIGINT
, CUST_FIRST_NAME VARCHAR(40)
, CUST_LAST_NAME VARCHAR(50)
, STREET_ADDRESS VARCHAR(50)
, POSTAL_CODE BIGINT
, CITY VARCHAR(30)
, STATE_PROVINCE VARCHAR(3)
, COUNTRY_ID VARCHAR(2)
, COUNTRY_NAME VARCHAR(30)
, CREDIT_LIMIT BIGINT
, CUST_EMAIL VARCHAR(50)
, PRIMARY_PHONE_NUMBER VARCHAR(30)
)
;

-- Cria tabela de representante de vendas
DROP TABLE IF EXISTS dw_sad.dim_vendedores;
CREATE TABLE dw_sad.dim_vendedores
(
  REPRESENTANTE_DIM_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY
, version INT
, date_from DATETIME
, date_to DATETIME
, SALESREP_ID BIGINT
, FIRST_NAME VARCHAR(30)
, LAST_NAME VARCHAR(50)
, EMAIL VARCHAR(50)
, PHONE_NUMBER VARCHAR(22)
, HIRE_DATE DATETIME
, JOB_ID VARCHAR(6)
, SALARY BIGINT
, COMMISSION_PCT INT
, MANAGER_ID BIGINT
, DEPARTMENT_ID BIGINT
)
;

-- Cria tabela de produtos
DROP TABLE IF EXISTS dw_sad.dim_produtos;
CREATE TABLE dw_sad.dim_produtos
(
  PRODUTO_DIM_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY
, version INT
, date_from DATETIME
, date_to DATETIME
, PRODUCT_ID BIGINT
, PRODUCT_NAME VARCHAR(40)
, MIN_PRICE BIGINT
, LIST_PRICE BIGINT
, PRODUCT_STATUS VARCHAR(17)
, SUPPLIER_ID BIGINT
, WARRANTY_PERIOD INT
, WEIGHT_CLASS BIGINT
, PRODUCT_DESCRIPTION TEXT
, CATEGORY_ID BIGINT
, SUB_CATEGORY_NAME VARCHAR(30)
, SUB_CATEGORY_DESCRIPTION VARCHAR(100)
, PARENT_CATEGORY_ID BIGINT
, CATEGORY_NAME VARCHAR(30)
)
;


-- Cria tabela de promoções
DROP TABLE IF EXISTS dw_sad.dim_promocoes;
CREATE TABLE dw_sad.dim_promocoes
(
  PROMO_DIM_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY
, version INT
, date_from DATETIME
, date_to DATETIME
, PROMO_ID BIGINT
, PROMO_NAME VARCHAR(30)
)
;

-- Cria tabela de datas
DROP TABLE IF EXISTS dw_sad.dim_data;
CREATE TABLE dw_sad.dim_data
(
  data_dim_id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY
, version INT
, date_from DATETIME
, date_to DATETIME
, dia_pedido DATETIME
, dia_do_ano INT
, mes INT
, ano INT
, quartil INT
, nome_mes VARCHAR(24)
, mes_ano DATETIME
)
;

-- Cria tabela de vendas
DROP TABLE IF EXISTS dw_sad.fato_vendas;
CREATE TABLE dw_sad.fato_vendas
(
  ORDER_ID BIGINT
, ORDER_TOTAL DOUBLE
, UNIT_PRICE DOUBLE
, QUANTITY BIGINT
, CLIENTE_DIM_ID BIGINT
, REPRESENTANTE_DIM_ID BIGINT
, PRODUTOS_DIM_ID BIGINT
, PROMO_DIM_ID BIGINT
, data_dim_id BIGINT
, GASTO_POR_ITEM DOUBLE
, REPRESENTACAO_ITEM DOUBLE
)
;

ALTER TABLE fato_vendas
ADD primary key (ORDER_id);

ALTER TABLE fato_vendas
ADD constraint vendas_produtos_fk
foreign key(PRODUTOS_DIM_ID) references dim_produtos(PRODUTOS_DIM_ID);

ALTER TABLE fato_vendas
ADD constraint vendas_promocoes_fk
foreign key(PROMO_DIM_ID) references dim_promocoes(PROMO_DIM_ID);

ALTER TABLE fato_vendas
ADD constraint vendas_vendedor_fk
foreign key(REPRESENTANTE_DIM_ID) references dim_vendedores(REPRESENTANTE_DIM_ID);

ALTER TABLE fato_vendas
ADD constraint vendas_clientes_fk
foreign key(CLIENTE_DIM_ID) references dim_clientes(CLIENTE_DIM_ID);

ALTER TABLE fato_vendas
ADD constraint vendas_data_fk
foreign key(data_dim_id) references dim_data(data_dim_id);

